{% set name = "aws-c-event-stream" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 051eac92b8d5955e2c83dcd42de94faa47854f8590ee884027ac0c9ba4c1bcbc

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("aws-c-event-stream", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
  host:
    - aws-c-common
    - aws-c-io
    - aws-checksums

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-event-stream${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libaws-c-event-stream.a  # [unix]
    - test -f $PREFIX/include/aws/event-stream/event_stream.h  # [unix]

about:
  home: https://github.com/awslabs/aws-c-event-stream
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of the vnd.amazon.eventstream content-type.

extra:
  recipe-maintainers:
    - xhochy
    - davidbrochart
