schema_version: 1

context:
  name: aws-c-event-stream
  version: "0.7.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/awslabs/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 88835b4c78462547917f622fd9dda45c991b7e356d9c07e2f0537d4d97fbd4fb

build:
  number: 0

requirements:
  build:
    - cmake !=3.19.0,!=3.19.1
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - ninja
  host:
    - aws-c-common
    - aws-c-io
    - aws-checksums
  run_exports:
    - ${{ pin_subpackage("aws-c-event-stream", upper_bound="x.x.x") }}

tests:
  - script:
      - if: unix
        then:
          - test -f $PREFIX/lib/libaws-c-event-stream${SHLIB_EXT}
          - test -f $PREFIX/include/aws/event-stream/event_stream.h
        else:
          - if not exist %LIBRARY_BIN%\aws-c-event-stream.dll exit 1
          - if not exist %LIBRARY_INC%\aws\event-stream\event_stream.h exit 1
about:
  license: Apache-2.0
  license_file: LICENSE
  summary: C99 implementation of the vnd.amazon.eventstream content-type.
  homepage: https://github.com/awslabs/aws-c-event-stream
  repository: https://github.com/awslabs/aws-c-event-stream

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
