schema_version: 1

context:
  name: aws-c-event-stream
  version: 0.5.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/awslabs/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 3a53a9d05f9e2fd06036a12854a8b4f05a0c4858bb5b8df8a30edba9de8532b5

build:
  number: 0

requirements:
  build:
    - cmake !=3.19.0,!=3.19.1
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - ninja
  host:
    - aws-c-common
    - aws-c-io
    - aws-checksums
  run_exports:
    - ${{ pin_subpackage("aws-c-event-stream", upper_bound="x.x.x") }}

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/lib/libaws-c-event-stream${SHLIB_EXT}
      - if: unix
        then: test -f $PREFIX/include/aws/event-stream/event_stream.h

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: C99 implementation of the vnd.amazon.eventstream content-type.
  homepage: https://github.com/awslabs/aws-c-event-stream

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
